Espaciolimite
1cgonza/lab-moviles pull request #1
Opened 2020-12-21 20:45 UTC by jeanniffer

2020-12-21 21:47 UTC, 1cgonza requested changes
Acá te mando unos comentarios. Antes de integrar, asegurate que corras desde el terminal el comando: `yarn build`, esto crea la versión optimizada para montar en el servidor. Los JS y CSS quedan minificados después de `yarn build`

2020-12-21 21:47 UTC, 1cgonza commented on docs/espacio-limite/index.html
> +    <meta property="og:url" content="https://metatags.io/" />
Esta URL debe ser: https://1cgonza.github.io/lab-moviles/espacio-limite/

2020-12-21 21:47 UTC, 1cgonza commented on docs/espacio-limite/index.html
> +      content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png"
Esta imagen es la predeterminada de metatags.io Cual sería la tuya?

2020-12-21 21:47 UTC, 1cgonza commented on docs/espacio-limite/index.html
> +            <h1 class="titulo">espacio, ¿límite? prueba</h1>
¿?

2020-12-21 21:47 UTC, 1cgonza commented on proyectos/espacio-limite/programa.js
> +  /*
Puede eliminar este comentario vacío.

2020-12-21 21:47 UTC, 1cgonza commented on proyectos/espacio-limite/programa.js
> +document.body.addEventListener('mousemove', (e) => {
Ah ya veo que estas probando pero no es el final. Si quieres sigue haciendo push con los cambios que eso actualiza este pull request. Cuando este listo lo agrego.

2020-12-23 21:31 UTC, jeanniffer commented on docs/espacio-limite/index.html
> +      content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png"
Sobre esto, hay alguna forma de probar que los links funcionen? Los cambié por href con el enlace de la carpeta

2020-12-30 22:08 UTC, 1cgonza commented on docs/espacio-limite/index.html
> +      content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png"
en este caso es un poco torpe la manera como estoy incluyendo las imágenes que se usan en HTML, seguramente en Rollup hay otra forma de hacerlo. Mira en 76b5c86 los cambios a `rollup.config.js` y la URL en HTML.

2020-12-30 22:12 UTC, 1cgonza commented on proyectos/espacio-limite/programa.js
> +document.body.addEventListener('mousemove', (e) => {
En este momento tienes este evento con el `mousemove` que supongo lo tenías para probar los puntos, pero lo vas a dejar así? no se si deja de funcionar en el celular porque si uno toca la pantalla se activa este evento y compite con el podometro, no?

2020-12-31 01:53 UTC, jeanniffer commented
Hmm, me salen unos errores que me confunden en archivos que no toco, por qué pasa eso? Me aseguré de hacer `yarn build` antes de hacer el PR.

Creo que ahora si está, voy a paso lento pero agarrando más confianza con git / github

2020-12-31 02:29 UTC, 1cgonza commented
Ya quedó integrado, hice algunos cambios porque FB se quejaba de algunas cosas pero revisa en este link: https://developers.facebook.com/tools/debug/ la url de tu proyecto: https://1cgonza.github.io/lab-moviles/espacio-limite/ 

Para twitter lo puedes probar en este: https://cards-dev.twitter.com/validator

2020-12-31 02:29 UTC, closed without merging

2020-12-31 02:30 UTC, 1cgonza commented
Hice merge resolviendo conflictos.